"Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 134, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 11:52:09 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 140, in openTriggerSocket\n    while handler.run_:\nUnboundLocalError: local variable 'handler' referenced before assignment\n Tue Feb 18 11:59:10 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 140, in openTriggerSocket\n    while handler.run_:\nUnboundLocalError: local variable 'handler' referenced before assignment\n Tue Feb 18 11:59:31 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 140, in openTriggerSocket\n    while handler.run_:\nUnboundLocalError: local variable 'handler' referenced before assignment\n Tue Feb 18 11:59:52 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 12:14:39 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 12:15:38 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 12:16:38 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 12:18:20 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 12:25:21 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 12:28:05 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 12:32:53 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 135, in openTriggerSocket\n    print connection.getHostName()\nAttributeError: '_socketobject' object has no attribute 'getHostName'\n Tue Feb 18 14:59:27 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 135, in openTriggerSocket\n    print connection.gethostname()\nAttributeError: '_socketobject' object has no attribute 'gethostname'\n Tue Feb 18 15:00:10 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 135, in openTriggerSocket\n    print s.gethostname()\nAttributeError: '_socketobject' object has no attribute 'gethostname'\n Tue Feb 18 15:00:27 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 143, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 15:01:51 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 140, in openTriggerSocket\n    while handler.run_:\nUnboundLocalError: local variable 'handler' referenced before assignment\n Tue Feb 18 15:05:06 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 15:05:47 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 15:07:00 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 15:10:08 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 15:27:18 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 15:28:03 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 15:29:01 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 15:44:50 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 16:00:38 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 16:01:54 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 16:04:06 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 16:06:09 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 140, in openTriggerSocket\n    while handler.run_:\nUnboundLocalError: local variable 'handler' referenced before assignment\n Tue Feb 18 16:29:04 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 143, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 16:33:38 2014\n""Traceback (most recent call last):\n  File \"/home/kristian/master_thesis/code/python/DAQ.py\", line 133, in openTriggerSocket\n    connection, addr = s.accept()     # Establish connection with client.\n  File \"/usr/lib/python2.7/socket.py\", line 202, in accept\n    sock, addr = self._sock.accept()\ntimeout: timed out\n Tue Feb 18 17:10:22 2014\n"